package com.alternatecomputing.jsvn.gui;

import com.alternatecomputing.jsvn.command.Command;
import com.alternatecomputing.jsvn.command.Move;
import com.alternatecomputing.jsvn.configuration.ConfigurationManager;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.Map;

/**
 *
 */
public class MoveDialog extends CommandDialog {
	private static final String DIALOG_TITLE = "Move";
	private static final String DIALOG_CAPTION = "Move Options";

	/**
     * constructor
     * @param parent parent frame
     * @param modal boolean indicating whether or not this dialog is modal
     */
        public MoveDialog(Frame parent, boolean modal) {
            super(parent, modal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 180));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel1.add(jTextField1, gridBagConstraints);

        jLabel1.setText("Source:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 60, 50, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Destination:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(31, 60, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.insets = new java.awt.Insets(31, 10, 1, 0);
        jPanel1.add(jTextField2, gridBagConstraints);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 50, 32);
        jPanel1.add(jButton1, gridBagConstraints);

        jLabel3.setText("Revision:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(30, 60, 22, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 23, 0);
        jPanel1.add(jTextField3, gridBagConstraints);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.insets = new java.awt.Insets(31, 10, 0, 32);
        jPanel1.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
		displayFileChooser(jTextField2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
		displayFileChooser(jTextField1);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void displayFileChooser(JTextField textField) {
		JFileChooser chooser;
		File currentWorkingDirectory = new File(textField.getText());
		if (currentWorkingDirectory.exists()) {
			// use the location in the text field
			chooser = new JFileChooser(currentWorkingDirectory);
		} else {
			currentWorkingDirectory = new File(ConfigurationManager.getInstance().getWorkingDirectory());
			if (currentWorkingDirectory.exists()) {
				// use the location of the working copy
				chooser = new JFileChooser(currentWorkingDirectory);
			} else {
				// don't know where to start
				chooser = new JFileChooser();
			}
		}

		chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		int action = chooser.showOpenDialog(new JFrame());
		if (action == JFileChooser.APPROVE_OPTION) {
			try {
				textField.setText(chooser.getSelectedFile().getCanonicalPath());
			} catch (IOException e) {
				textField.setText("");
			}
		}
	}

	/** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm

    }//GEN-LAST:event_exitForm

    /**
	 * creates the appropriate command to run and populated the given Map with appropriate arguments to configure the command
     * @param args map of arguments to be passed into the returned command
     * @return implementation of Command to execute with the given configured args
     */
    protected Command buildCommand(Map args) {
		args.put(Move.SOURCE, jTextField1.getText().trim());
		args.put(Move.DESTINATION, jTextField2.getText().trim());
		String revision = jTextField3.getText().trim();
		if (!"".equals(revision)) {
			args.put(Move.REVISION, revision);
		}
		return new Move();
    }

    /**
	 * gets the captions to be displayed in the options panel
     * @return options panel caption
     */
    protected String getDialogCaption() {
        return DIALOG_CAPTION;
    }

    /**
	 * gets the title of the dialog
     * @return dialog title
     */
    protected String getDialogTitle() {
        return DIALOG_TITLE;
    }

    /**
	 * gets the panel in which all options for the command are configured
     * @return options panel
     */
    protected JPanel getOptionsPanel() {
        initComponents();
        return jPanel1;
    }

    /**
	 * determines whether the selected options are valid before the command is allowed to execute
     * @return options validity indicator
     */
    protected boolean isValidOptions() {
		String source =jTextField1.getText().trim();
		if (source.length() == 0) {
			JOptionPane.showMessageDialog(this.getContentPane(), "Must specify a source");
			return false;
		}
		String destination =jTextField2.getText().trim();
		if (destination.length() == 0) {
			JOptionPane.showMessageDialog(this.getContentPane(), "Must specify a destination");
			return false;
		}
		return true;
    }

	/**
	 * Invoked when an action occurs.
	 */
	public void actionPerformed(ActionEvent e) {
	}

	/**
	 * sets the targets upon which the command should run
	 * @param targets
	 */
	public void setTargets(String targets) {
		super.setTargets(targets);
		// if only one target is selected, then default it into the source text field
		if (targets.indexOf(" ") < 0) {
			jTextField1.setText(targets);
		} else {
			jTextField1.setText("");
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
